### ISSUE TITLE
equi2 in R running in docker

### ISSUE THREAD

**Issue by PJGator** [billdenney/equil2#1]
I am trying to get equil2 function to work in R within a Docker Container.   I can successfully run the function in R and it is awesome!!!  I am trying to be able to call the function from a web application with the function running in an R image running in a Docker container.  We are using R's Plumber library in the docker image which acts like a REST API which can be called from anything.  This all works, but once I introduce the equil2 library, it fails because it doesn’t know about equil2.
 
I have been trying for weeks and cannot get the library to load when I run the container.  I am guessing it is the version of R that is loaded but not sure.  I feel like I have tried everything. Here is my dockerfile that starts the container:
 
FROM rocker/r-ver:4.0
 
RUN apt-get update -qq && \
    apt-get install -y \
      pandoc \
      libssl-dev \
      libcurl4-gnutls-dev \
      libxml2-dev
 
RUN R -e "install.packages(c('plumber', 'dplyr', 'plotly'))"
 
RUN R -e "install.packages('units')"
RUN R -e "install.packages('equil2')"
 
COPY equil2-api.R equil2-api.R
 
EXPOSE 8000
 
ENTRYPOINT ["R", "-e", "library(plumber); plumber::pr('equil2-api.R')$run(port=8000, host='0.0.0.0')"]
 
Here is my equi2-api.R:

#* @get /equil2calc
function(time, exponent = 1.06) {
  library(equil2)
  equil2(
    sodium_mEq_L=units::set_units(45, "mmol_sodium/L"),
    potassium_mEq_L=units::set_units(55, "mmol_potassium/L"),
    calcium_mg_dL=units::set_units(15, "mg_calcium/dL"),
    magnesium_mg_dL=units::set_units(15, "mg_magnesium/dL"),
    ammonia_mEq_L=units::set_units(10, "ug_ammonia/dL"),
    chloride_mEq_L=units::set_units(75, "mmol_chloride/L"),
    phosphate_mg_dL=units::set_units(100, "mg_phosphate/dL"),
    sulfate_mg_dL=units::set_units(20, "mEq_sulfate/L"),
    oxalate_mg_dL=units::set_units(10, "mg_oxalate/L"),
    citrate_mg_dL=units::set_units(400, "mg_citrate/L"),
    pH=5.5,
    urate_mg_dL=units::set_units(50, "mg_urate/dL")
  )
}

Everything comes up, but when it hits the line to execute library(equi2) it fails saying cannot find library.  

This is how I call it using curl:

curl --location 'http://127.0.0.1:8000/equil2calc?time=34'

This is the output:
![image](https://github.com/billdenney/equil2/assets/35575377/a7ad64f7-df2b-4a30-a527-6c4644024c78)

I wanted to reach out in case anyone had any insight to versioning of the R images that your function should work in.   Help!

~Paul

**Comment by billdenney** [comment]
It looks like `equil2` is not available for R version 4.0.  When I ran it directly in the container, I saw:

```
> install.packages("equil2")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning message:
package ‘equil2’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

Using R 4.3 got around this error and gave another error related to missing libraries:

```
> library(equil2)
Error: package or namespace load failed for ‘equil2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/units/libs/units.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
```

**Comment by PJGator** [comment]
@billdenney  Thanks!   That got me closer.  I changed to version 4.3 and then got the same error you get when trying to call library(equil2).   I was able to open the terminal and successfully run  install.packages("udunits2"), then install.packages("equil2)" and hit the API and it worked!!  I got back the result json.   Excited, I then tried to add the same into my Dockerfile and it failed.  

The frustrating part is that I've now tried to reproduce building the container and manually installing udunits2 and I cannot get it to work.

**Comment by billdenney** [comment]
You need to add libudunits2-dev to the apt installation part: https://github.com/r-quantities/units#installation

**Comment by PJGator** [comment]
That did the trick!   Thank you @billdenney   

This is my final Dockerfile:

```
FROM rocker/r-ver:4.3

RUN apt-get update -qq && \
    apt-get install -y \
      pandoc \
      libssl-dev \
      libcurl4-gnutls-dev \
      libxml2-dev \
      libudunits2-dev

RUN R -e "install.packages(c('plumber', 'dplyr', 'plotly'))"

COPY equil2-api.R equil2-api.R
COPY install_packages.R install_packages.R

RUN Rscript install_packages.R

EXPOSE 8000

ENTRYPOINT ["R", "-e", "library(plumber); plumber::pr('equil2-api.R')$run(port=8000, host='0.0.0.0')"] 

```
This is the equil2-api.R

```
#* @get /equil2calc
function(time, exponent = 1.06) {
  library(equil2)
  equil2(
    sodium_mEq_L=units::set_units(45, "mmol_sodium/L"),
    potassium_mEq_L=units::set_units(55, "mmol_potassium/L"),
    calcium_mg_dL=units::set_units(15, "mg_calcium/dL"),
    magnesium_mg_dL=units::set_units(15, "mg_magnesium/dL"),
    ammonia_mEq_L=units::set_units(10, "ug_ammonia/dL"),
    chloride_mEq_L=units::set_units(75, "mmol_chloride/L"),
    phosphate_mg_dL=units::set_units(100, "mg_phosphate/dL"),
    sulfate_mg_dL=units::set_units(20, "mEq_sulfate/L"),
    oxalate_mg_dL=units::set_units(10, "mg_oxalate/L"),
    citrate_mg_dL=units::set_units(400, "mg_citrate/L"),
    pH=5.5,
    urate_mg_dL=units::set_units(50, "mg_urate/dL")
  )
}

```
Here is my install_packages.R

`install.packages("equil2")`

**Comment by billdenney** [comment]
Great!
